// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-82_ClOrRMxesmaiPEx-q07F1so4qvCg',
    appId: '1:159856558393:web:8352b7b7c18f9666a428e8',
    messagingSenderId: '159856558393',
    projectId: 'fir-crud-c622f',
    authDomain: 'fir-crud-c622f.firebaseapp.com',
    storageBucket: 'fir-crud-c622f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7orwBE-hYW8lUcReAy4LT6Mm4NyQzueo',
    appId: '1:159856558393:android:80977ccf63ae2f7ca428e8',
    messagingSenderId: '159856558393',
    projectId: 'fir-crud-c622f',
    storageBucket: 'fir-crud-c622f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD83zgi0vdmdzG2jhp30wKF6Xtu0hjADA',
    appId: '1:159856558393:ios:a2d608eb872ca800a428e8',
    messagingSenderId: '159856558393',
    projectId: 'fir-crud-c622f',
    storageBucket: 'fir-crud-c622f.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD83zgi0vdmdzG2jhp30wKF6Xtu0hjADA',
    appId: '1:159856558393:ios:a2d608eb872ca800a428e8',
    messagingSenderId: '159856558393',
    projectId: 'fir-crud-c622f',
    storageBucket: 'fir-crud-c622f.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-82_ClOrRMxesmaiPEx-q07F1so4qvCg',
    appId: '1:159856558393:web:d1cca68845f31839a428e8',
    messagingSenderId: '159856558393',
    projectId: 'fir-crud-c622f',
    authDomain: 'fir-crud-c622f.firebaseapp.com',
    storageBucket: 'fir-crud-c622f.firebasestorage.app',
  );
}
